### ISSUE TITLE
能不能把键盘的字母和IO去掉 或者支持自定义

### ISSUE THREAD

**Issue by a1906404** [loyalwind/WJLicensePlateKeyboard#5]
能不能把键盘的字母和IO去掉，因为车牌号里面没有字母I和O，或者支持自定义，有些时候需要根据业务需求改变一下汉字顺序或者是字母顺序，如果不支持自定义数组的话就不能通过pod方式引到工程了

**Comment by loyalwind** [comment]
已经更新了1.1.0版本，去除了字母 I和O，并另外支持自定义功能

**Comment by loyalwind** [comment]
已解决更新到1.1.0版本

发自我的 iPhone 12
